name: CI/CD Pipeline - Simple

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: harshad41/wisecow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGEAGE }}:${{ github.sha }}

    - name: Deploy Notification
      run: |
        echo "Docker image built and pushed successfully!"
        echo "Manual deployment required: kubectl apply -f k8s/"

  health-checks:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Application Health Check
      run: |
        chmod +x scripts/application_health_checker.sh
        ./scripts/application_health_checker.sh

    - name: System Health Check
      run: |
        chmod +x scripts/system_health_monitor.sh
        ./scripts/system_health_monitor.sh

    - name: Log Analysis
      run: |
        python scripts/log_analyzer.py --sample
        # Or use actual log files if available in CI
