name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
        cache-to: type=inline

  # For now, let's skip deployment in CI/CD until we set up a proper K8s cluster
  # We'll manually deploy for this project
  test-deployment:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Minikube for testing
      uses: medyagh/setup-minikube@v2
      with:
        driver: docker

    - name: Test Kubernetes manifests
      run: |
        # Validate manifests without applying
        kubectl apply --dry-run=client -f k8s/deployment.yaml
        kubectl apply --dry-run=client -f k8s/tls-setup.yaml
        echo "Kubernetes manifests are valid!"